; Script generated by Antigravity IDE for Smart Exam Grader
; Packaging via Inno Setup 6

#define MyAppName "Smart Exam Grader"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Fahrur Rozi K"
#define MyAppURL "https://github.com/rfahur11/smart-exam-grader"
#define MyAppExeName "Jalankan_Smart_Grader.bat"

[Setup]
AppId={{8B849C73-9AC9-47F2-81D6-11C283B47021}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\Programs\SmartExamGrader
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=LICENSE
OutputDir=dist
OutputBaseFilename=Setup_SmartExamGrader_v1.0.0
SetupIconFile=assets\icon.ico
UninstallDisplayIcon={app}\assets\icon.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "app.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "main.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "run_anbuso_grader.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "requirements.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "Jalankan_Smart_Grader.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "SYSTEM_STATE.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "assets\*"; DestDir: "{app}\assets"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "src\*"; DestDir: "{app}\src"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "data\templates\*"; DestDir: "{app}\data\templates"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "data\sample_inputs\*"; DestDir: "{app}\data\sample_inputs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "data\outputs\.gitkeep"; DestDir: "{app}\data\outputs"; Flags: ignoreversion
Source: "docs\*"; DestDir: "{app}\docs"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\icon.ico"
Name: "{group}\Dokumentasi Portfolio"; Filename: "{app}\docs\carousel.html"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\icon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\assets\prerequisites\python-3.11.9-amd64.exe"; Parameters: "/quiet InstallAllUsers=0 PrependPath=1 Include_test=0 Include_pip=1"; StatusMsg: "Memeriksa dan memasang Python 3.11 Runtime..."; Flags: runhidden; Check: NeedsPython
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall nowait skipifsilent

[Code]
function NeedsPython(): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  if Exec('cmd.exe', '/c python -c "import sys; exit(0)"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    if ResultCode = 0 then
    begin
      Result := False;
      Exit;
    end;
  end;
  if FileExists(ExpandConstant('{localappdata}\Programs\Python\Python311\python.exe')) then
  begin
    Result := False;
    Exit;
  end;
  if FileExists(ExpandConstant('{localappdata}\Programs\Python\Python310\python.exe')) then
  begin
    Result := False;
    Exit;
  end;
end;
